// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngwnqnvkseiexvlvxcup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nd25xbnZrc2VpZXh2bHZ4Y3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1NDIxMDIsImV4cCI6MjA5MjExODEwMn0.NUl4bewu8eUBXW5WgEmhJEeQGKEi0Lhomy0N34JOmEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});